Presentation.Mvc/Areas/AdminPanel/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Domain.Models;
using Infrastructure.Contexts;
using Microsoft.AspNetCore.Authorization;
using Application.Interfaces;

namespace Presentation.Mvc.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    [Authorize]
    public class CategoriesController : Controller
    {
        private readonly IUnitOfWork _context;

        public CategoriesController(IUnitOfWork context)
        {
            _context = context;
        }

        // GET: AdminPanel/Categories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Categories.GetAsync());
        }

       

        // GET: AdminPanel/Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AdminPanel/Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Title,Icon")] Category category)
        {
            if (ModelState.IsValid)
            {
                await _context.Categories.InsertAsync(category);
                await _context.Commit();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: AdminPanel/Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.GetByIDAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: AdminPanel/Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Title,Icon")] Category category)
        {
            if (id != category.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _context.Categories.UpdateAsync(category);
                    await _context.Commit();
                }
                catch (DbUpdateConcurrencyException)
                {

                    if (await _context.Categories.GetByIDAsync(category.Id) == null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }


        // GET: AdminPanel/Categories/DetailsAndDelete/5
        public async Task<IActionResult> DetailsAndDelete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .GetByIDAsync(id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: AdminPanel/Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories.GetByIDAsync(id);
            await _context.Categories.DeleteAsync(category);
            await _context.Commit();
            return RedirectToAction(nameof(Index));
        }


    }
}

Presentation.Mvc/Areas/AdminPanel/Controllers/SubCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Domain.Models;
using Infrastructure.Contexts;
using Microsoft.AspNetCore.Authorization;
using Application.Interfaces;
using Newtonsoft.Json;
using Presentation.Mvc.Models;

namespace Presentation.Mvc.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    [Authorize]
    public class SubCategoriesController : Controller
    {
        private readonly IUnitOfWork _context;

        public SubCategoriesController(IUnitOfWork context)
        {
            _context = context;
        }

        // GET: AdminPanel/SubCategories
        public async Task<IActionResult> Index()
        {
            if((await _context.Categories.GetAsync()).Count() == 0)
            {
                TempData["SweetAlert"] = JsonConvert.SerializeObject(new SweetAlert()
                {
                    Title = "توجه",
                    Text = "ابتدا یک دسته بندی منو ایجاد کنید",
                    Icon = SweetAlertIcon.info,
                    ShowCloseButton = false,
                    CancelButtonText = "",
                    ComfirmButtonText = "باشــــه",
                    ShowCancelButton = false
                });

                return RedirectToAction("Index","Categories");
            }

            var applicationDbContext = await _context.SubCategories.GetAsync(includeProperties: "Category");
            return View(applicationDbContext.ToList());
        }

       
        // GET: AdminPanel/SubCategories/Create
        public async Task<IActionResult> CreateAsync()
        {
            if ((await _context.Categories.GetAsync()).Count() == 0)
            {
                TempData["SweetAlert"] = JsonConvert.SerializeObject(new SweetAlert()
                {
                    Title = "توجه",
                    Text = "ابتدا یک دسته بندی منو ایجاد کنید",
                    Icon = SweetAlertIcon.info,
                    ShowCloseButton = false,
                    CancelButtonText = "",
                    ComfirmButtonText = "باشــــه",
                    ShowCancelButton = false
                });

                return RedirectToAction("Index", "Categories");
            }

            ViewData["CategoryId"] = new SelectList(await _context.Categories.GetAsync(), "Id", "Title");
            return View();
        }

        // POST: AdminPanel/SubCategories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Title,Icon,CategoryId")] SubCategory subCategory)
        {
            if (ModelState.IsValid)
            {
                await _context.SubCategories.InsertAsync(subCategory);
                await _context.Commit();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(await _context.Categories.GetAsync(), "Id", "Title", subCategory.CategoryId);
            return View(subCategory);
        }

        // GET: AdminPanel/SubCategories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subCategory = await _context.SubCategories.GetByIDAsync(id);
            if (subCategory == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(await _context.Categories.GetAsync(), "Id", "Title", subCategory.CategoryId);
            return View(subCategory);
        }

        // POST: AdminPanel/SubCategories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Title,Icon,CategoryId")] SubCategory subCategory)
        {
            if (id != subCategory.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                   await _context.SubCategories.UpdateAsync(subCategory);
                    await _context.Commit();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (_context.SubCategories.GetByIDAsync(subCategory.Id)==null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(await _context.Categories.GetAsync(), "Id", "Title", subCategory.CategoryId);
            return View(subCategory);
        }

        // GET: AdminPanel/SubCategories/DetailsAndDelete/5
        public async Task<IActionResult> DetailsAndDelete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subCategory = (await _context.SubCategories.GetAsync(
                where: n => n.Id == id,
                includeProperties: "Category")).FirstOrDefault();

            if (subCategory == null)
            {
                return NotFound();
            }

            return View(subCategory);
        }


        // POST: AdminPanel/SubCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var subCategory = await _context.SubCategories.GetByIDAsync(id);
           await _context.SubCategories.DeleteAsync(subCategory);
            await _context.Commit();
            return RedirectToAction(nameof(Index));
        }

        
    }
}

Presentation.Mvc/Areas/AdminPanel/Views/Categories/Create.cshtml
@model Domain.Models.Category

@{
    ViewData["Title"] = "ایجاد دسته بندی منو";
}


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Icon" class="control-label"></label>
                <input asp-for="Icon" class="form-control" />
                <span asp-validation-for="Icon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="ثبت" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">بازگشت</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Presentation.Mvc/Areas/AdminPanel/Views/Categories/DetailsAndDelete.cshtml
@model Domain.Models.Category
@inject Application.Interfaces.IUnitOfWork _context;
@{
    ViewData["Title"] = Model.Title;

    var subCategories = (await _context.SubCategories.GetAsync(n => n.CategoryId == Model.Id)).ToList();
}


<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Icon)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Icon)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" id="btn-submit" value="حذف" class="btn btn-danger" />

        <a asp-action="Index" class="btn btn-default">بازگشت</a>
    </form>

    <hr />
    <h3>زیرمنو ها</h3>
    <hr />
    <table class="table" style="direction:rtl">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">نام</th>
                <th scope="col">عنوان</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>

         
            @{
                int counter = 1;


                foreach (var item in subCategories)
                {

                    <tr>
                        <th scope="row">@counter</th>
                        <td>@item.Name</td>
                        <td>@item.Title</td>
                        <td><a asp-action="DetailsAndDelete" asp-route-Id="@item.Id" asp-controller="SubCategories" class="btn btn-sm btn-primary">نمایش</a></td>
                    </tr>


                    counter++;
                }

                }


        </tbody>
    </table>
</div>

@section Scripts{

    <script>
        $('#btn-submit').on('click', function (e) {
            e.preventDefault();
            var form = $(this).parents('form');
            swal.fire({
                title: "حذف دسته بندی منو",
                text: "هشدار جدی: تمامی زیر منو ها و دسته بندی ها و محصولات این دسته بندی حذف میشوند",
                icon: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "حذف",
                cancelButtonText: "لغو"

            }).then(
                function () { form.submit(); },
                function () { return false; });;
        });
    </script>
}

Presentation.Mvc/Areas/AdminPanel/Views/Categories/Edit.cshtml
@model Domain.Models.Category

@{
    ViewData["Title"] = "ویرایش دسته بندی منو";
}



<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Icon" class="control-label"></label>
                <input asp-for="Icon" class="form-control" />
                <span asp-validation-for="Icon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="ویرایش" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">بازگشت</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Presentation.Mvc/Areas/AdminPanel/Views/Categories/Index.cshtml
@model IEnumerable<Domain.Models.Category>

@{
    ViewData["Title"] = "لیست دسته بندی های منو";
}


<p>
    <a asp-action="Create" class="btn btn-primary">ایجاد</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Icon)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Icon)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">ویرایش</a> |
                <a asp-action="DetailsAndDelete" asp-route-id="@item.Id">نمایش</a> |
                <a asp-action="DetailsAndDelete" asp-route-id="@item.Id">حذف</a>
            </td>
        </tr>
}
    </tbody>
</table>