Presentation.Mvc/Areas/AdminPanel/Controllers/SubCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Domain.Models;
using Infrastructure.Contexts;
using Microsoft.AspNetCore.Authorization;
using Application.Interfaces;
using Newtonsoft.Json;
using Presentation.Mvc.Models;

namespace Presentation.Mvc.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    [Authorize]
    public class SubCategoriesController : Controller
    {
        private readonly IUnitOfWork _context;

        public SubCategoriesController(IUnitOfWork context)
        {
            _context = context;
        }

        // GET: AdminPanel/SubCategories
        public async Task<IActionResult> Index()
        {
            if((await _context.Categories.GetAsync()).Count() == 0)
            {
                TempData["SweetAlert"] = JsonConvert.SerializeObject(new SweetAlert()
                {
                    Title = "توجه",
                    Text = "ابتدا یک دسته بندی منو ایجاد کنید",
                    Icon = SweetAlertIcon.info,
                    ShowCloseButton = false,
                    CancelButtonText = "",
                    ComfirmButtonText = "باشــــه",
                    ShowCancelButton = false
                });

                return RedirectToAction("Index","Categories");
            }

            var applicationDbContext = await _context.SubCategories.GetAsync(includeProperties: "Category");
            return View(applicationDbContext.ToList());
        }

       
        // GET: AdminPanel/SubCategories/Create
        public async Task<IActionResult> CreateAsync()
        {
            if ((await _context.Categories.GetAsync()).Count() == 0)
            {
                TempData["SweetAlert"] = JsonConvert.SerializeObject(new SweetAlert()
                {
                    Title = "توجه",
                    Text = "ابتدا یک دسته بندی منو ایجاد کنید",
                    Icon = SweetAlertIcon.info,
                    ShowCloseButton = false,
                    CancelButtonText = "",
                    ComfirmButtonText = "باشــــه",
                    ShowCancelButton = false
                });

                return RedirectToAction("Index", "Categories");
            }

            ViewData["CategoryId"] = new SelectList(await _context.Categories.GetAsync(), "Id", "Title");
            return View();
        }

        // POST: AdminPanel/SubCategories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Title,Icon,CategoryId")] SubCategory subCategory)
        {
            if (ModelState.IsValid)
            {
                await _context.SubCategories.InsertAsync(subCategory);
                await _context.Commit();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(await _context.Categories.GetAsync(), "Id", "Title", subCategory.CategoryId);
            return View(subCategory);
        }

        // GET: AdminPanel/SubCategories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subCategory = await _context.SubCategories.GetByIDAsync(id);
            if (subCategory == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(await _context.Categories.GetAsync(), "Id", "Title", subCategory.CategoryId);
            return View(subCategory);
        }

        // POST: AdminPanel/SubCategories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Title,Icon,CategoryId")] SubCategory subCategory)
        {
            if (id != subCategory.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                   await _context.SubCategories.UpdateAsync(subCategory);
                    await _context.Commit();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (_context.SubCategories.GetByIDAsync(subCategory.Id)==null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(await _context.Categories.GetAsync(), "Id", "Title", subCategory.CategoryId);
            return View(subCategory);
        }

        // GET: AdminPanel/SubCategories/DetailsAndDelete/5
        public async Task<IActionResult> DetailsAndDelete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subCategory = (await _context.SubCategories.GetAsync(
                where: n => n.Id == id,
                includeProperties: "Category")).FirstOrDefault();

            if (subCategory == null)
            {
                return NotFound();
            }

            return View(subCategory);
        }


        // POST: AdminPanel/SubCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var subCategory = await _context.SubCategories.GetByIDAsync(id);
           await _context.SubCategories.DeleteAsync(subCategory);
            await _context.Commit();
            return RedirectToAction(nameof(Index));
        }

        
    }
}

Presentation.Mvc/Areas/AdminPanel/Controllers/SubCategoryItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Domain.Models;
using Infrastructure.Contexts;
using Microsoft.AspNetCore.Authorization;
using Application.Interfaces;
using Newtonsoft.Json;
using Presentation.Mvc.Models;

namespace Presentation.Mvc.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    [Authorize]
    public class SubCategoryItemsController : Controller
    {
        private readonly IUnitOfWork _context;

        public SubCategoryItemsController(IUnitOfWork context)
        {
            _context = context;
        }

        // GET: AdminPanel/SubCategoryItems
        public async Task<IActionResult> Index()
        {
            if ((await _context.SubCategories.GetAsync()).Count() == 0)
            {
                TempData["SweetAlert"] = JsonConvert.SerializeObject(new SweetAlert()
                {
                    Title = "توجه",
                    Text = "ابتدا یک دسته بندی زیرمنو ایجاد کنید",
                    Icon = SweetAlertIcon.info,
                    ShowCloseButton = false,
                    CancelButtonText = "",
                    ComfirmButtonText = "باشــــه",
                    ShowCancelButton = false
                });

                return RedirectToAction("Index", "SubCategories");
            }

            var applicationDbContext = await _context.SubCategoryItems.GetAsync(includeProperties: "SubCategory");
            return View(applicationDbContext.ToList());
        }

       

        // GET: AdminPanel/SubCategoryItems/Create
        public async Task<IActionResult> Create()
        {
            if ((await _context.SubCategories.GetAsync()).Count() == 0)
            {
                TempData["SweetAlert"] = JsonConvert.SerializeObject(new SweetAlert()
                {
                    Title = "توجه",
                    Text = "ابتدا یک دسته بندی زیرمنو ایجاد کنید",
                    Icon = SweetAlertIcon.info,
                    ShowCloseButton = false,
                    CancelButtonText = "",
                    ComfirmButtonText = "باشــــه",
                    ShowCancelButton = false
                });

                return RedirectToAction("Index", "SubCategories");
            }

            var catList = new[] { new { Id = 0, Title = "همه" } }.ToList();

            catList.AddRange((await _context.Categories.GetAsync()).Select(n=>new {Id=n.Id,Title=n.Title }));
            ViewData["CategoryId"] = new SelectList(catList, "Id", "Title");

            ViewData["SubCategoryId"] = new SelectList(await _context.SubCategories.GetAsync(), "Id", "Title");
            ViewData["SubCategoriesJSON"] = JsonConvert.SerializeObject((await _context.SubCategories.GetAsync()).Select(n => new { Id = n.Id, Title = n.Title, CategoryId = n.CategoryId }));

            return View();
        }

        // POST: AdminPanel/SubCategoryItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Title,Icon,SubCategoryId")] SubCategoryItem subCategoryItem)
        {
            if (ModelState.IsValid)
            {
                await _context.SubCategoryItems.InsertAsync(subCategoryItem);
                await _context.Commit();
                return RedirectToAction(nameof(Index));
            }

            var catList = new[] { new { Id = 0, Title = "انتخاب کنید" } }.ToList();

            catList.AddRange((await _context.Categories.GetAsync()).Select(n => new { Id = n.Id, Title = n.Title }));
            ViewData["CategoryId"] = new SelectList(catList, "Id", "Title", (await _context.SubCategories.GetByIDAsync(subCategoryItem.SubCategoryId)).CategoryId);
          
           ViewData["SubCategoryId"] = new SelectList(await _context.SubCategories.GetAsync(), "Id", "Title", subCategoryItem.SubCategoryId);
            ViewData["SubCategoriesJSON"] = JsonConvert.SerializeObject((await _context.SubCategories.GetAsync()).Select(n => new { Id = n.Id, Title = n.Title, CategoryId = n.CategoryId }));

            return View(subCategoryItem);
        }

        // GET: AdminPanel/SubCategoryItems/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subCategoryItem = await _context.SubCategoryItems.GetByIDAsync(id);
            if (subCategoryItem == null)
            {
                return NotFound();
            }

            int categoryId= (await _context.SubCategories.GetByIDAsync(subCategoryItem.SubCategoryId)).CategoryId;

            var catList = new[] { new { Id = 0, Title = "همه" } }.ToList();

            catList.AddRange((await _context.Categories.GetAsync()).Select(n => new { Id = n.Id, Title = n.Title }));
            ViewData["CategoryId"] = new SelectList(catList, "Id", "Title",categoryId );
          
            ViewData["SubCategoryId"] = new SelectList(await _context.SubCategories.GetAsync(n=>n.CategoryId==categoryId), "Id", "Title", subCategoryItem.SubCategoryId);
            ViewData["SubCategoriesJSON"] = JsonConvert.SerializeObject((await _context.SubCategories.GetAsync()).Select(n => new { Id = n.Id, Title = n.Title, CategoryId = n.CategoryId }));
            return View(subCategoryItem);
        }

        // POST: AdminPanel/SubCategoryItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Title,Icon,SubCategoryId")] SubCategoryItem subCategoryItem)
        {
            if (id != subCategoryItem.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _context.SubCategoryItems.UpdateAsync(subCategoryItem);
                    await _context.Commit();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (_context.SubCategoryItems.GetByIDAsync(subCategoryItem.Id) == null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }


            int categoryId = (await _context.SubCategories.GetByIDAsync(subCategoryItem.SubCategoryId)).CategoryId;

            var catList = new[] { new { Id = 0, Title = "همه" } }.ToList();

            catList.AddRange((await _context.Categories.GetAsync()).Select(n => new { Id = n.Id, Title = n.Title }));
            ViewData["CategoryId"] = new SelectList(catList, "Id", "Title", categoryId);

            ViewData["SubCategoryId"] = new SelectList(await _context.SubCategories.GetAsync(n => n.CategoryId == categoryId), "Id", "Title", subCategoryItem.SubCategoryId);
            ViewData["SubCategoriesJSON"] = JsonConvert.SerializeObject((await _context.SubCategories.GetAsync()).Select(n=>new { Id=n.Id,Title=n.Title,CategoryId=n.CategoryId}));


            return View(subCategoryItem);
        }

        // GET: AdminPanel/SubCategoryItems/DetailsAndDelete/5
        public async Task<IActionResult> DetailsAndDelete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subCategoryItem = (await _context.SubCategoryItems.GetAsync(
                where: n => n.Id == id,
                includeProperties: "SubCategory")).FirstOrDefault();

            if (subCategoryItem == null)
            {
                return NotFound();
            }

            return View(subCategoryItem);
        }


        // POST: AdminPanel/SubCategoryItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var subCategoryItem = await _context.SubCategoryItems.GetByIDAsync(id);
            await _context.SubCategoryItems.DeleteAsync(subCategoryItem);
            await _context.Commit();
            return RedirectToAction(nameof(Index));
        }

    }
}

Presentation.Mvc/Areas/AdminPanel/Views/SubCategories/Create.cshtml
@model Domain.Models.SubCategory

@{
    ViewData["Title"] = "افزودن زیرمنو";
}


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Icon" class="control-label"></label>
                <input asp-for="Icon" class="form-control" />
                <span asp-validation-for="Icon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class ="form-control" asp-items="ViewBag.CategoryId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="ثبت" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">بازگشت</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Presentation.Mvc/Areas/AdminPanel/Views/SubCategories/DetailsAndDelete.cshtml
@model Domain.Models.SubCategory
@inject Application.Interfaces.IUnitOfWork _context;
@{
    ViewData["Title"] = Model.Title;

    var subCategoryItems = (await _context.SubCategoryItems.GetAsync(n => n.SubCategoryId == Model.Id)).ToList();
}


<div>
  
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Icon)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Icon)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Category.Id)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" id="btn-submit" value="حذف" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-default">بازگشت</a>
    </form>

    <hr />
    <h3>موارد زیرمنو(دسته بندی محصولات زیرمنو)</h3>
    <hr />
    <table class="table" style="direction:rtl">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">نام</th>
                <th scope="col">عنوان</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>


            @{
                int counter = 1;


                foreach (var item in subCategoryItems)
                {

                    <tr>
                        <th scope="row">@counter</th>
                        <td>@item.Name</td>
                        <td>@item.Title</td>
                        <td><a asp-action="DetailsAndDelete" asp-route-Id="@item.Id" asp-controller="SubCategoryItems" class="btn btn-sm btn-primary">نمایش</a></td>
                    </tr>


                    counter++;
                }

            }


        </tbody>
    </table>

</div>

@section Scripts{

    <script>
        $('#btn-submit').on('click', function (e) {
            e.preventDefault();
            var form = $(this).parents('form');
            swal.fire({
                title: "حذف دسته بندی زیرمنو",
                text: "هشدار جدی: تمامی زیردسته بندی ها و محصولات های آن ها حذف میشوند",
                icon: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "حذف",
                cancelButtonText: "لغو"

            }).then(
                function () { form.submit(); },
                function () { return false; });;
        });
    </script>
}

Presentation.Mvc/Areas/AdminPanel/Views/SubCategories/Edit.cshtml
@model Domain.Models.SubCategory

@{
    ViewData["Title"] = "ویرایش زیرمنو";
}


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Icon" class="control-label"></label>
                <input asp-for="Icon" class="form-control" />
                <span asp-validation-for="Icon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="ویرایش" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">بازگشت</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Presentation.Mvc/Areas/AdminPanel/Views/SubCategories/Index.cshtml
@model IEnumerable<Domain.Models.SubCategory>

@{
    ViewData["Title"] = "لیست زیرمنو ها";
}


<p>
    <a asp-action="Create" class="btn btn-primary">ایجاد</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Icon)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Icon)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Title)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">ویرایش</a> |
                <a asp-action="DetailsAndDelete" asp-route-id="@item.Id">نمایش</a> |
                <a asp-action="DetailsAndDelete" asp-route-id="@item.Id">حذف</a>
            </td>
        </tr>
}
    </tbody>
</table>